version: "3.9"
services:
  fastapi:
    build:
      context: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./nosql:/app
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: