name: Pylint

on:
  push:
    branches:
      - main
  workflow_call:
  pull_request:
    branches:
      - "**"

concurrency:
  group: linting-${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-11, macos-12, macos-13, ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.10","3.11","3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "${{ matrix.os }}" == "macos-11" ] || [ "${{ matrix.os }}" == "macos-12" ] || [ "${{ matrix.os }}" == "macos-13" ]; then
          brew install libffi
        else
          sudo apt-get install -y libffi-dev python3-cffi python3-cffi
        fi
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint **/*.py
